<a href="https://colab.research.google.com/github/Yo-17/CardsAgainstHumanity_Proofyourstatesucks/blob/main/Sesion%2008.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.10/dist-packages (8.1.0)
Requirement already satisfied: protobuf<=4.21.12,>=4.21.1 in /usr/local/lib/python3.10/dist-packages (from mysql-connector-python) (4.21.12)

In [49]:
import pandas as pd
import mysql.connector

In [50]:
#En produccion esto siempre ira en variables de entorno
mysql = mysql.connector.connect(
    host = "ec2-54-203-29-73.us-west-2.compute.amazonaws.com",
    port = 3306,
    user = "data",
    password = "khQ9--mp6LWq97iA",
    database = "movielens"
)

In [51]:
mysql

In [52]:
cursor = mysql.cursor()

In [84]:
cursor.execute("SELECT * FROM users")

In [85]:
result = cursor.fetchall()

In [ ]:
result

In [45]:
#es importante cerrar nuestro cursor para no utilizar memoria extra en nuestra computadora
#cursor.close()

True

In [101]:
df_users = pd.DataFrame(result, columns=['user_id', 'gender', 'age', 'occupation', 'cp'])

df_users.head(10)

   user_id gender  age  occupation     cp
0        1      F    1          10  48067
1        2      M   56          16  70072
2        3      M   25          15  55117
3        4      M   45           7  02460
4        5      M   25          20  55455
5        6      F   50           9  55117
6        7      M   35           1  06810
7        8      M   25          12  11413
8        9      M   25          17  61614
9       10      F   35           1  95370

In [102]:
df_users=df_users.set_index('user_id')

In [103]:
df_users.isna().sum().sort_values()

gender        0
age           0
occupation    0
cp            0
dtype: int64

In [104]:
df_users.head()

        gender  age  occupation     cp
user_id
1            F    1          10  48067
2            M   56          16  70072
3            M   25          15  55117
4            M   45           7  02460
5            M   25          20  55455

In [95]:
cursor.execute("SELECT * FROM movies")
result2 = cursor.fetchall()

In [ ]:
result2

In [98]:
df_movies = pd.DataFrame(result2, columns=['movie_id', 'title', 'genre'])

df_movies.head(10)

   movie_id                               title                         genre
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [93]:
df_movies=df_movies.set_index('movie_id')

In [ ]:
df_movies.head(10)

In [96]:
cursor.execute("SELECT * FROM ratings")
result3 = cursor.fetchall()

In [ ]:
result3

In [99]:
df_ratings = pd.DataFrame(result3, columns=['user_id', 'movie_id', 'rating', 'timestamp'])

In [100]:
df_ratings.head(10)

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291
5        1      1197       3  978302268
6        1      1287       5  978302039
7        1      2804       5  978300719
8        1       594       4  978302268
9        1       919       4  978301368

In [107]:
cursor.execute("SELECT * FROM occupations")
result4 = cursor.fetchall()
df_occupations = pd.DataFrame(result4, columns=['occupation_id', 'description'])
df_occupations = df_occupations.set_index('occupation_id', drop=True)

In [108]:
df_occupations.head(10)

                          description
occupation_id
0              other or not specified
1                   academic/educator
2                              artist
3                      clerical/admin
4                college/grad student
5                    customer service
6                  doctor/health care
7                executive/managerial
8                              farmer
9                           homemaker